#
#    Survive The Night
#   Plugin Configuration
#

fuel-can-hash: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFlYTgyNTE1MGIwNmU2NWUyY2ViNTkzYWZlMzQyZGNhNTZkZGExMmJmNmM5Njk2ZmI4MmY5MGRjZDQyM2FiIn19fQ=="

#
#   Thanks for downloading!
#     Make sure to leave a review on the plugin,
#     and feel free to contact me in a DM or on the resource thread
#     about any bugs or features you would like fixed/implemented!
#
#         ◎[▪‿▪]◎
#